version: '3'

vars:
  CLUSTER_NAME: argo-all-the-things

tasks:
  create-cluster:
    run: once
    cmds:
      - k3d cluster create {{.CLUSTER_NAME}} --api-port 6443 -p 8080:80@loadbalancer
    vars:
      NUM_WORKER_NODES: 3

  delete-cluster:
    cmds:
      - k3d cluster delete {{.CLUSTER_NAME}}

  tf-apply:
    dir: ./terraform/infra
    cmds:
      - terraform init
      - terraform apply --auto-approve

  tf-destroy:
    dir: ./terraform/infra
    cmds:
      - terraform destroy --auto-approve

  up:
    cmds:
      - task: create-cluster
      - task: tf-apply

  down:
    cmds:
      - task: tf-destroy
      - task: delete-cluster
